### ISSUE TITLE
about robotiq2F140 control

### ISSUE THREAD

**Issue by xxhaonan** [githubuser0xFFFF/py_robotiq_gripper#1]
Hello！ Thanks for your code ，I want control robotiq2F140 by the same method like robotiq2F85，could you tell me where I need change？ thanks for your reply

**Comment by xxhaonan** [comment]
![Q8 (_TRYC)~@FGLZ 8VFL7A](https://user-images.githubusercontent.com/81416871/227079528-6c6bb3db-4853-44c5-ac61-aa684d546534.png)
I don‘t seem to be able to connect with robotiq2F140 by socket

**Comment by xxhaonan** [comment]
hostname was set as same as ip of ur5，port is 63352

**Comment by xxhaonan** [comment]
I think the problem maybe by reason of the port 63352？ because I use robotiq2F140’s port is different from robotiq2F85

**Comment by githubuser0xFFFF** [comment]
This is just a fork - maybe you should ask the author of the project
